//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace gzpi.Web.tb_attachment {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblf_id;
		protected global::System.Web.UI.WebControls.TextBox txtf_FileName;
		protected global::System.Web.UI.WebControls.TextBox txtf_CreateTime;
		protected global::System.Web.UI.WebControls.TextBox txtf_FlieSize;
		protected global::System.Web.UI.WebControls.TextBox txtf_Creator;
		protected global::System.Web.UI.WebControls.TextBox txtf_FileType;
		protected global::System.Web.UI.WebControls.TextBox txtf_FilePath;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
