//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace gzpi.Web.tb_attachment {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblf_id;
	protected global::System.Web.UI.WebControls.Label lblf_FileName;
	protected global::System.Web.UI.WebControls.Label lblf_CreateTime;
	protected global::System.Web.UI.WebControls.Label lblf_FlieSize;
	protected global::System.Web.UI.WebControls.Label lblf_Creator;
	protected global::System.Web.UI.WebControls.Label lblf_FileType;
	protected global::System.Web.UI.WebControls.Label lblf_FilePath;


       
    }
}
