//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace gzpi.Web.tb_供应商信息 {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblID;
		protected global::System.Web.UI.WebControls.TextBox txt供应商名称;
		protected global::System.Web.UI.WebControls.TextBox txt地址;
		protected global::System.Web.UI.WebControls.TextBox txt邮政编码;
		protected global::System.Web.UI.WebControls.TextBox txt联系电话;
		protected global::System.Web.UI.WebControls.TextBox txt传真;
		protected global::System.Web.UI.WebControls.TextBox txt开户银行;
		protected global::System.Web.UI.WebControls.TextBox txt账户;
		protected global::System.Web.UI.WebControls.TextBox txt联系人;
		protected global::System.Web.UI.WebControls.TextBox txt主要产品或服务;
		protected global::System.Web.UI.WebControls.TextBox txt评估日期;
		protected global::System.Web.UI.WebControls.TextBox txt评估结论;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
