//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace gzpi.Web.tb_供应商信息 {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblID;
	protected global::System.Web.UI.WebControls.Label lbl供应商名称;
	protected global::System.Web.UI.WebControls.Label lbl地址;
	protected global::System.Web.UI.WebControls.Label lbl邮政编码;
	protected global::System.Web.UI.WebControls.Label lbl联系电话;
	protected global::System.Web.UI.WebControls.Label lbl传真;
	protected global::System.Web.UI.WebControls.Label lbl开户银行;
	protected global::System.Web.UI.WebControls.Label lbl账户;
	protected global::System.Web.UI.WebControls.Label lbl联系人;
	protected global::System.Web.UI.WebControls.Label lbl主要产品或服务;
	protected global::System.Web.UI.WebControls.Label lbl评估日期;
	protected global::System.Web.UI.WebControls.Label lbl评估结论;


       
    }
}
