//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace gzpi.Web.tb_资产信息 {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblID;
		protected global::System.Web.UI.WebControls.TextBox txt固定资产编号;
		protected global::System.Web.UI.WebControls.TextBox txt固定资产名称;
		protected global::System.Web.UI.WebControls.TextBox txt规格型号;
		protected global::System.Web.UI.WebControls.TextBox txt使用部门;
		protected global::System.Web.UI.WebControls.TextBox txt存放地点;
		protected global::System.Web.UI.WebControls.TextBox txt使用状况;
		protected global::System.Web.UI.WebControls.TextBox txt开始使用日期;
		protected global::System.Web.UI.WebControls.TextBox txt原值;
		protected global::System.Web.UI.WebControls.TextBox txt发票号;
		protected global::System.Web.UI.WebControls.TextBox txt出厂号;
		protected global::System.Web.UI.WebControls.TextBox txt制造商;
		protected global::System.Web.UI.WebControls.TextBox txt销货单位;
		protected global::System.Web.UI.WebControls.TextBox txt折旧及报废情况;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
