//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace gzpi.Web.tb_资产信息 {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblID;
	protected global::System.Web.UI.WebControls.Label lbl固定资产编号;
	protected global::System.Web.UI.WebControls.Label lbl固定资产名称;
	protected global::System.Web.UI.WebControls.Label lbl规格型号;
	protected global::System.Web.UI.WebControls.Label lbl使用部门;
	protected global::System.Web.UI.WebControls.Label lbl存放地点;
	protected global::System.Web.UI.WebControls.Label lbl使用状况;
	protected global::System.Web.UI.WebControls.Label lbl开始使用日期;
	protected global::System.Web.UI.WebControls.Label lbl原值;
	protected global::System.Web.UI.WebControls.Label lbl发票号;
	protected global::System.Web.UI.WebControls.Label lbl出厂号;
	protected global::System.Web.UI.WebControls.Label lbl制造商;
	protected global::System.Web.UI.WebControls.Label lbl销货单位;
	protected global::System.Web.UI.WebControls.Label lbl折旧及报废情况;


       
    }
}
